/** Mapas de alias PT/EN → chave interna, usados para reconhecer variações de rótulo do FutOdds. */

export const infoAliases: Record<string, string> = {
  competicao: "competition",
  competition: "competition",
  liga: "competition",
  temporada: "season",
  season: "season",
  data: "matchDate",
  date: "matchDate",
  horario: "matchTime",
  hora: "matchTime",
  time: "matchTime",
  estadio: "venue",
  venue: "venue",
  local: "venue",
  cidade: "city",
  city: "city",
  pais: "country",
  country: "country",
};

export const oddsAliases: Record<string, keyof typeof oddsShape> = {
  casa: "home",
  "1": "home",
  empate: "draw",
  x: "draw",
  fora: "away",
  visitante: "away",
  "2": "away",
  "over 0.5 ht": "over05HT",
  "over 0.5 1t": "over05HT",
  "over 1.5": "over15",
  "over 2.5": "over25",
  "under 2.5": "under25",
  "under 3.5": "under35",
  "btts sim": "bttsYes",
  "ambas marcam sim": "bttsYes",
  "btts nao": "bttsNo",
  "ambas marcam nao": "bttsNo",
};

const oddsShape = {
  home: 0,
  draw: 0,
  away: 0,
  over05HT: 0,
  over15: 0,
  over25: 0,
  under25: 0,
  under35: 0,
  bttsYes: 0,
  bttsNo: 0,
};

export const probabilityAliases: Record<string, string> = {
  casa: "home",
  empate: "draw",
  fora: "away",
  visitante: "away",
  "btts sim": "bttsYes",
  "ambas marcam sim": "bttsYes",
  "over 2.5": "over25",
  "under 3.5": "under35",
  "over 0.5 ht": "over05HT",
  "over 0.5 1t": "over05HT",
  "primeiro a marcar casa": "firstToScoreHome",
  "primeiro a marcar fora": "firstToScoreAway",
  "placar base": "expectedScore",
  "placar-base": "expectedScore",
  "faixa de gols": "expectedGoalRange",
};

export const lastFiveAliases: Record<string, string> = {
  forma: "form",
  form: "form",
  "over 0.5 ht": "over05HT",
  "over 0.5 1t": "over05HT",
  "over 2.5": "over25",
  btts: "bttsYes",
  "ambas marcam": "bttsYes",
};

export const lastTwentyAliases: Record<string, string> = {
  ppg: "ppg",
  vitorias: "wins",
  empates: "draws",
  derrotas: "losses",
  "media de gols": "avgGoals",
  "gols marcados": "goalsFor",
  "gols sofridos": "goalsAgainst",
  "gols marcados 1t": "firstHalfGoalsFor",
  "gols primeiro tempo": "firstHalfGoalsFor",
  "gols segundo tempo": "secondHalfGoalsFor",
  "over 2.5": "over25",
  "under 2.5": "under25",
  "clean sheet": "cleanSheet",
  "falhou em marcar": "failedToScore",
  "marcou primeiro": "scoredFirst",
  "marcou apos 70": "scoredAfter70",
  "marcou apos os 70 minutos": "scoredAfter70",
  xg: "xg",
  "xg contra": "xgAgainst",
  chutes: "shots",
  "chutes no alvo": "shotsOnTarget",
  conversao: "conversion",
  escanteios: "corners",
  cartoes: "cards",
  posse: "possession",
  ataques: "attacks",
  "ataques perigosos": "dangerousAttacks",
  faltas: "fouls",
  impedimentos: "offsides",
};

export const percentFields = new Set([
  "wins_pct",
  "over05HT",
  "over15",
  "over25",
  "under25",
  "under35",
  "bttsYes",
  "bttsNo",
  "cleanSheet",
  "failedToScore",
  "scoredFirst",
  "scoredAfter70",
  "conversion",
  "possession",
  "home",
  "draw",
  "away",
  "firstToScoreHome",
  "firstToScoreAway",
]);
